#
# Gitlab build file for GOR.
#
include:
  - project: wuxi-nextcode/sdev/gitlab-ci-scripts
    file: /auto-ci-workflow.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  #- template: License-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

variables:
  RELEASABLE_BRANCH: master
  AUTO_DEPLOY_BRANCH: master
  AUTO_DEPLOY_ENV_REPO: wuxi-nextcode/kube-env/dev/platform-dev-kube-env
  DOWNSTREAM_KUBE_SUBCHART: sequence-miner
  DOCKER_HUB_REPO: nextcode/spark
  RELEASE_ENV_REPO: wuxi-nextcode/kube-env/customer-kube-env
  AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--build-arg ORG_GRADLE_PROJECT_artifactory_password --build-arg ORG_GRADLE_PROJECT_artifactory_user --build-arg ORG_GRADLE_PROJECT_gitlab_gor_maven_packages_token"
  DOCKER_BUILDKIT: "1"
  JAVA_BUILDER_IMAGE: nextcode/builderimg-java:openjdk14
  GIT_SUBMODULE_STRATEGY: none
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"

  # Vars for build resources
  KUBERNETES_CPU_REQUEST: 4
  KUBERNETES_CPU_LIMIT: 6
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi

stages:
  - build
  - test
  - publish
  - trigger-cross-projects
  - promote
  - release
  - deploy

build:
  tags:
    - gitlab-org