#
# Gitlab build file for GOR.
#

variables:
  JAVA_BUILDER_IMAGE: nextcode/builderimg-java:openjdk8
  GIT_SUBMODULE_STRATEGY: none
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"
  RELEASABLE_BRANCH: master                                         # Optional (master is the default).  If this matches the current branch, the built image will be releasable with a semver tag.


.on-releasable-branch-only:
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $RELEASABLE_BRANCH

.on-releasable-or-release-branch-only:
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $RELEASABLE_BRANCH
      - $CI_COMMIT_REF_NAME =~ /^release\/v(0|[1-9]\d*)\.(0|[1-9]\d*)$/

.on-releasable-or-semver-tag-only:
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $RELEASABLE_BRANCH
      - $CI_COMMIT_TAG =~ /^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-([1-9]\d*|[\da-z-]*[a-z-][\da-z-]*)(\.([1-9]\d*|[\da-z-]*[a-z-][\da-z-]*))*)?(\+[\da-z-]+(\.[\da-z-]+)*)?$/


stages:
  - build
  - test
  - publish
  - trigger-cross-projects


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle


build:
  stage: build
  image: "$JAVA_BUILDER_IMAGE"
  script: ./gradlew assemble
  tags:
    - iceland
  only:
    - branches
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - "build"
      - "**/build"
      - ".gradle"


.build_cache:
  extends: build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "build"
      - "**/build"
      - ".gradle"


.test:
  extends: .build_cache
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    reports:
      junit:
        - "*/*/*/*/TEST-*.xml"
        - "*/*/*/*/*/TEST-*.xml"
        # Seems like ** does not work properly (even though it is used in the Gitlab docutmentation)
        #- "**/build/test-results/test/**/TEST-*.xml"


unittest:
  extends: .test
  script: ./gradlew --continue test


slowtest:
  extends: .test
  script: ./gradlew --continue slowTest


integrationtest:
  extends: .test
  script: ./gradlew --continue integrationTest


# This codequality block is needed to work around https://gitlab.com/gitlab-org/gitlab/issues/12274
code_quality:
  extends:
    - .on-releasable-or-release-branch-only
  stage: test
  tags:
    - iceland
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
    expire_in: 1 week


license_management:
  extends:
    - .build_cache
    - .on-releasable-or-release-branch-only
  stage: test
  variables:
    # There is no need to run tests or generate sphinx documentation for license management
    # analysis, however, the license management plugin calls the build task so we have to manually
    # disable tests and documentation generation.
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dskip.tests=true -Dskip.documentation=true"


dependency_scanning:
  stage: test
  tags:
    - iceland
  variables:
    # There is no need to run tests or generate sphinx documentation for license management
    # analysis, however, the license management plugin calls the build task so we have to manually
    # disable tests and documentation generation.
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dskip.tests=true -Dskip.documentation=true"
  artifacts:
    paths: [gl-dependency-scanning-report.json]


publish:
  extends:
    - .build_cache
    - .on-releasable-or-semver-tag-only
  stage: publish
  script: ./gradlew publish -x test -x slowTest -x integrationTest


gor-services:
  extends: .on-releasable-branch-only
  stage: trigger-cross-projects
  trigger:
    project:  wuxi-nextcode/wxnc-gor/gor-services
    branch:   develop


include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Security/License-Management.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
