#
# Gitlab build file for GOR-spark.
#

variables:
  RELEASABLE_BRANCH: master
  AUTO_DEPLOY_BRANCH: master
  DOCKER_HUB_REPO: nextcode/spark
  AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--build-arg ORG_GRADLE_PROJECT_artifactory_password --build-arg ORG_GRADLE_PROJECT_artifactory_user --build-arg ORG_GRADLE_PROJECT_gitlab_gor_maven_packages_token"
  DOCKER_BUILDKIT: "1"
  JAVA_BUILDER_IMAGE: registry.gitlab.com/wuxi-nextcode/sdev/build-images/java-17:latest
  GIT_SUBMODULE_STRATEGY: none
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"

  # Vars for build resources
  KUBERNETES_CPU_REQUEST: 4
  KUBERNETES_CPU_LIMIT: 6
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  extends: .on-branches
  stage: build
  image: "$JAVA_BUILDER_IMAGE"
  script: echo "hello"
    #- |
    #  if [[ -z "$CI_COMMIT_TAG" ]]; then
    #    if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then
    #      ./gradlew -PREGISTRY_USER=${CI_REGISTRY_USER} -PREGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD} -PAPPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG} -PAPPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA} assemble jib
    #    else
    #      ./gradlew -PREGISTRY_USER=${CI_REGISTRY_USER} -PREGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD} -PAPPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG} -PAPPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA} assemble
    #    fi
    #  else
    #    ./gradlew -PREGISTRY_USER=${CI_REGISTRY_USER} -PREGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD} -PAPPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE} -PAPPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG} assemble jib
    #  fi
  tags:
    - gitlab-build-01
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - "build"
      - "**/build"
      - ".gradle"


.build_cache:
  extends: build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "build"
      - "**/build"
      - ".gradle"


.test:
  extends: .build_cache
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    reports:
      junit:
        - "*/*/*/*/TEST-*.xml"
        - "*/*/*/*/*/TEST-*.xml"
        # Seems like ** does not work properly (even though it is used in the Gitlab docutmentation)
        #- "**/build/test-results/test/**/TEST-*.xml"

#unittest:
#  extends: .test
#  script: ./gradlew --continue test

publish:
  extends:
    - .build_cache
    - .on-releasable-branch
  stage: release
  script: ./gradlew publish -x test -x slowTest -x integrationTest

include:
  - project: wuxi-nextcode/sdev/gitlab-ci-scripts
    file: /auto-ci-workflow.yml
