apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: gorquery
  namespace: gorkube
spec:
  type: Java
  mode: cluster
  image: nextcode/spark:2.0.7
  imagePullPolicy: Always
  imagePullSecrets:
    - dockerhub-nextcode-download-credentials
  mainApplicationFile: local:///opt/spark/jars/gor-spark-2.0.7.jar
  mainClass: org.gorpipe.spark.redis.RedisBatchConsumer
  sparkVersion: 3.3.0
  dynamicAllocation:
    enabled: true
    initialExecutors: 2
    minExecutors: 0
    maxExecutors: 100
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 1
    onSubmissionFailureRetryInterval: 20
  sparkConf:
    spark.driver.extraClassPath: "/opt/spark/classpath/*"
  volumes:
    - name: mntcsa
      persistentVolumeClaim:
        claimName: pvc-gor-mnt-csa
    - name: mntcache
      persistentVolumeClaim:
        claimName: pvc-gor-mnt-cache
  driver:
    cores: 2
    coreLimit: 2400m
    memory: 4g
    labels:
      version: v3.2.0
    volumeMounts:
      - name: csa
        mountPath: /mnt/csa
        readOnly: true
      - name: cache
        mountPath: /mnt/cache
    securityContext:
      runAsUser: 3000
      fsGroup: 3000
  executor:
    cores: 2
    instances: 2
    memory: 8g
    labels:
      version: v3.2.0
    volumeMounts:
      - name: csa
        mountPath: /mnt/csa
        readOnly: true
      - name: cache
        mountPath: /mnt/cache
    securityContext:
      runAsUser: 3000
      fsGroup: 3000
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent-0.16.1.jar"
      port: 8090
