apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: gorquery
  namespace: gorkube
spec:
  type: Java
  mode: cluster
  image: nextcode/spark:1.4.9
  imagePullPolicy: Always
  imagePullSecrets:
    - dockerhub-nextcode-download-credentials
  mainApplicationFile: local:///opt/spark/jars/gor-spark-1.4.9.jar
  mainClass: org.gorpipe.spark.redis.RedisBatchConsumer
  sparkVersion: 3.1.2
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 1
    onSubmissionFailureRetryInterval: 20
  sparkConf:
    spark.kubernetes.driver.volumes.persistentVolumeClaim.volume.mount.path: /mnt/csa/volumes
    spark.kubernetes.driver.volumes.persistentVolumeClaim.volume.mount.readOnly: "false"
    spark.kubernetes.driver.volumes.persistentVolumeClaim.volume.mount.subPath: volumes
    spark.kubernetes.driver.volumes.persistentVolumeClaim.volume.options.claimName: pvc-phenocat-nfs
    spark.kubernetes.executor.volumes.persistentVolumeClaim.volume.mount.path: /mnt/csa/volumes
    spark.kubernetes.executor.volumes.persistentVolumeClaim.volume.mount.readOnly: "false"
    spark.kubernetes.executor.volumes.persistentVolumeClaim.volume.mount.subPath: volumes
    spark.kubernetes.executor.volumes.persistentVolumeClaim.volume.options.claimName: pvc-phenocat-nfs
    spark.kubernetes.driver.volumes.persistentVolumeClaim.data.mount.path: /mnt/csa/data
    spark.kubernetes.driver.volumes.persistentVolumeClaim.data.mount.readOnly: "true"
    spark.kubernetes.driver.volumes.persistentVolumeClaim.data.mount.subPath: data
    spark.kubernetes.driver.volumes.persistentVolumeClaim.data.options.claimName: pvc-sm-nfs
    spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.path: /mnt/csa/data
    spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.readOnly: "true"
    spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.subPath: data
    spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.claimName: pvc-sm-nfs
  driver:
    cores: 1
    coreLimit: 1200m
    memory: 1500m
    labels:
      version: v3.1.2
    securityContext:
      runAsUser: 3000
      fsGroup: 3000
  executor:
    cores: 1
    instances: 1
    memory: 900m
    labels:
      version: v3.1.2
    securityContext:
      runAsUser: 3000
      fsGroup: 3000
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent-0.15.0.jar"
      port: 8090
